version: "3"

services:
  nginx_container:
    container_name: nginx
    image: alishukurov/nginx-task17:latest
    ports:
      - "80:80"
    depends_on:
      - apache_container

  apache_container:
    container_name: apache
    image: alishukurov/apache-task17:latest
    ports:
      - "8080:80"